### ISSUE TITLE
Save state

### ISSUE THREAD

**Issue by solarflare47** [uberhalit/CitraTouchControl#1]
Hello can you help me with the savestate thing. I am playing fire emblem and I loaded up a bookmark. I click save savegame and I think it saves? However when I click load savegame it keeps saying it wants to overwrite the old savegame and it won't load the savegame I saved. Please help I really need help on this b/c this chapter I am playing is glitched and sometimes it freezes when a unit attacks and I don't want to restart everytime I encounter this glitch, so I am relying on this savestate thing. Please and thank  you.

**Comment by uberhalit** [comment]
This feature does nothing else than backing up your current savegame folder. If you select "Load Savegames" the current savegame folder will be overwritten with the backup. In the case of Fire Emblem you'll have to create a bookmark during the battle, when back in menu use "Save Savegames" and then proceed with the battle. After you screwed up you reload the game and during the main menu phase you choose "Load Savegames". Now your previous bookmark will show up and you can continue the battle where you made the backup.
