### ISSUE TITLE
Generalize this to work with arbitrary programs?

### ISSUE THREAD

**Issue by kyle-kc** [uberhalit/CitraTouchControl#2]
Hey, I think this project is super cool! I was wondering how hard you think it would be to generalize this to work with any arbitrary program? This way you could play a remote session with any game running on your PC, theoretically. You could even have a drag-and-drop feature to set up your own controller layout. Is that something that seems feasible to you?

**Comment by uberhalit** [comment]
Hi, sorry for the long wait.

It certainly wouldn't be too hard but as I am only using it for Citra and *Citra* is basically in the title I won't add support for additional applications. You can however create a fork and extend its functionality yourself.
